export {
  load,
  save,
  initializeCache,
  cleanupLegacyLargeLocalStorage,
  checkMigrationNeeded,
  migrateData,
  getStorageStatus,
  remove,
  saveBatch,
  loadBatch,
  checkStorageQuota,
  clearAllData,
  smartLoad,
  smartSave,
  smartRemove,
  setBulkStorageRestoreInProgress,
  isBulkStorageRestoreInProgress,
} from '../../utils/storage';

