/**
 * AI财务管理系统
 * 管理AI的余额、收入、支出记录
 */

import { AIFinanceData, FinanceTransaction, IncomeConfig } from '../types';
import { smartLoad, smartSave } from './storage';

const FINANCE_STORAGE_KEY = 'ai_finance_data';

/**
 * 获取所有AI的财务数据
 */
const getAllFinanceData = async (): Promise<AIFinanceData[]> => {
  try {
    const data = await smartLoad(FINANCE_STORAGE_KEY);
    return data || [];
  } catch (error) {
    console.error('加载财务数据失败:', error);
    return [];
  }
};

/**
 * 保存财务数据
 */
const saveAllFinanceData = async (data: AIFinanceData[]): Promise<void> => {
  try {
    await smartSave(FINANCE_STORAGE_KEY, data);
  } catch (error) {
    console.error('保存财务数据失败:', error);
  }
};

/**
 * 获取指定AI的财务数据
 */
export const getAIFinanceData = async (aiId: string): Promise<AIFinanceData> => {
  const allData = await getAllFinanceData();
  const existing = allData.find(d => d.aiId === aiId);
  
  if (existing) {
    return existing;
  }
  
  // 创建新的财务数据
  const newData: AIFinanceData = {
    aiId,
    balance: 1000, // 初始余额
    totalIncome: 1000,
    totalExpense: 0,
    transactions: [{
      id: `trans_${Date.now()}`,
      timestamp: Date.now(),
      type: 'income',
      amount: 1000,
      category: '初始资金',
      description: '系统赠送的初始资金',
      autoGenerated: true
    }],
    incomeConfigs: [],
    settings: {
      allowNegativeBalance: false,
      notifyOnLowBalance: true,
      lowBalanceThreshold: 100
    }
  };
  
  allData.push(newData);
  await saveAllFinanceData(allData);
  return newData;
};

/**
 * 更新AI财务数据
 */
const updateAIFinanceData = async (data: AIFinanceData): Promise<void> => {
  const allData = await getAllFinanceData();
  const index = allData.findIndex(d => d.aiId === data.aiId);
  
  if (index >= 0) {
    allData[index] = data;
  } else {
    allData.push(data);
  }
  
  await saveAllFinanceData(allData);
};

/**
 * 添加交易记录
 */
export const addTransaction = async (
  aiId: string,
  type: 'income' | 'expense',
  amount: number,
  category: string,
  description: string,
  relatedUserId?: string,
  relatedMessageId?: string,
  autoGenerated: boolean = false
): Promise<boolean> => {
  try {
    const financeData = await getAIFinanceData(aiId);
    
    // 检查支出是否超出余额
    if (type === 'expense' && !financeData.settings.allowNegativeBalance) {
      if (financeData.balance < amount) {
        console.warn(`AI ${aiId} 余额不足，无法完成支出`);
        return false;
      }
    }
    
    // 创建交易记录
    const transaction: FinanceTransaction = {
      id: `trans_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: Date.now(),
      type,
      amount,
      category,
      description,
      relatedUserId,
      relatedMessageId,
      autoGenerated
    };
    
    // 更新余额和总计
    if (type === 'income') {
      financeData.balance += amount;
      financeData.totalIncome += amount;
    } else {
      financeData.balance -= amount;
      financeData.totalExpense += amount;
    }
    
    // 添加交易记录
    financeData.transactions.unshift(transaction); // 最新的放在前面
    
    // 限制交易记录数量（保留最近1000条）
    if (financeData.transactions.length > 1000) {
      financeData.transactions = financeData.transactions.slice(0, 1000);
    }
    
    await updateAIFinanceData(financeData);
    
    console.log(`✅ AI ${aiId} ${type === 'income' ? '收入' : '支出'} ¥${amount}，当前余额: ¥${financeData.balance}`);
    return true;
  } catch (error) {
    console.error('添加交易记录失败:', error);
    return false;
  }
};

/**
 * 添加收入配置
 */
export const addIncomeConfig = async (
  aiId: string,
  config: Omit<IncomeConfig, 'lastIncomeTime' | 'nextIncomeTime'>
): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  
  const now = Date.now();
  const newConfig: IncomeConfig = {
    ...config,
    lastIncomeTime: 0,
    nextIncomeTime: now + calculateNextIncomeDelay(config.frequency)
  };
  
  financeData.incomeConfigs.push(newConfig);
  await updateAIFinanceData(financeData);
};

/**
 * 更新收入配置
 */
export const updateIncomeConfig = async (
  aiId: string,
  configIndex: number,
  updates: Partial<IncomeConfig>
): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  
  if (configIndex >= 0 && configIndex < financeData.incomeConfigs.length) {
    financeData.incomeConfigs[configIndex] = {
      ...financeData.incomeConfigs[configIndex],
      ...updates
    };
    await updateAIFinanceData(financeData);
  }
};

/**
 * 删除收入配置
 */
export const removeIncomeConfig = async (
  aiId: string,
  configIndex: number
): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  financeData.incomeConfigs.splice(configIndex, 1);
  await updateAIFinanceData(financeData);
};

/**
 * 计算下次收入延迟（毫秒）
 */
const calculateNextIncomeDelay = (frequency: IncomeConfig['frequency']): number => {
  switch (frequency) {
    case 'daily':
      return 24 * 60 * 60 * 1000; // 1天
    case 'weekly':
      return 7 * 24 * 60 * 60 * 1000; // 7天
    case 'monthly':
      return 30 * 24 * 60 * 60 * 1000; // 30天
    case 'random':
      // 随机1-7天
      const days = 1 + Math.random() * 6;
      return days * 24 * 60 * 60 * 1000;
    default:
      return 24 * 60 * 60 * 1000;
  }
};

/**
 * 处理自动收入（在App启动或定时检查时调用）
 */
export const processAutoIncome = async (aiId: string): Promise<void> => {
  try {
    const financeData = await getAIFinanceData(aiId);
    const now = Date.now();
    let hasUpdate = false;
    
    for (let i = 0; i < financeData.incomeConfigs.length; i++) {
      const config = financeData.incomeConfigs[i];
      
      if (!config.enabled) continue;
      
      // 检查是否到了收入时间
      if (now >= config.nextIncomeTime) {
        // 计算实际收入金额
        let amount = config.baseAmount;
        if (config.randomRange) {
          const [min, max] = config.randomRange;
          amount = min + Math.random() * (max - min);
          amount = Math.round(amount * 100) / 100; // 保留两位小数
        }
        
        // 添加收入记录
        await addTransaction(
          aiId,
          'income',
          amount,
          config.description,
          `${config.description} - ${new Date().toLocaleDateString()}`,
          undefined,
          undefined,
          true
        );
        
        // 更新下次收入时间
        config.lastIncomeTime = now;
        config.nextIncomeTime = now + calculateNextIncomeDelay(config.frequency);
        hasUpdate = true;
      }
    }
    
    if (hasUpdate) {
      await updateAIFinanceData(financeData);
    }
  } catch (error) {
    console.error(`处理AI ${aiId} 自动收入失败:`, error);
  }
};

/**
 * 批量处理所有AI的自动收入
 */
export const processAllAutoIncome = async (): Promise<void> => {
  try {
    const allData = await getAllFinanceData();
    for (const data of allData) {
      await processAutoIncome(data.aiId);
    }
  } catch (error) {
    console.error('批量处理自动收入失败:', error);
  }
};

/**
 * 获取余额
 */
export const getBalance = async (aiId: string): Promise<number> => {
  const data = await getAIFinanceData(aiId);
  return data.balance;
};

/**
 * 检查余额是否充足
 */
export const checkBalance = async (aiId: string, amount: number): Promise<boolean> => {
  const data = await getAIFinanceData(aiId);
  if (data.settings.allowNegativeBalance) {
    return true;
  }
  return data.balance >= amount;
};

/**
 * 获取交易历史（可选分类和日期范围筛选）
 */
export const getTransactionHistory = async (
  aiId: string,
  filters?: {
    type?: 'income' | 'expense';
    category?: string;
    startDate?: number;
    endDate?: number;
    limit?: number;
  }
): Promise<FinanceTransaction[]> => {
  const data = await getAIFinanceData(aiId);
  let transactions = [...data.transactions];
  
  // 应用筛选
  if (filters) {
    if (filters.type) {
      transactions = transactions.filter(t => t.type === filters.type);
    }
    if (filters.category) {
      transactions = transactions.filter(t => t.category === filters.category);
    }
    if (filters.startDate) {
      transactions = transactions.filter(t => t.timestamp >= filters.startDate!);
    }
    if (filters.endDate) {
      transactions = transactions.filter(t => t.timestamp <= filters.endDate!);
    }
    if (filters.limit) {
      transactions = transactions.slice(0, filters.limit);
    }
  }
  
  return transactions;
};

/**
 * 获取财务统计
 */
export const getFinanceStats = async (aiId: string): Promise<{
  balance: number;
  totalIncome: number;
  totalExpense: number;
  thisMonthIncome: number;
  thisMonthExpense: number;
  todayTransactionCount: number;
}> => {
  const data = await getAIFinanceData(aiId);
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).getTime();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  
  const thisMonthTransactions = data.transactions.filter(t => t.timestamp >= monthStart);
  const todayTransactions = data.transactions.filter(t => t.timestamp >= todayStart);
  
  return {
    balance: data.balance,
    totalIncome: data.totalIncome,
    totalExpense: data.totalExpense,
    thisMonthIncome: thisMonthTransactions
      .filter(t => t.type === 'income')
      .reduce((sum, t) => sum + t.amount, 0),
    thisMonthExpense: thisMonthTransactions
      .filter(t => t.type === 'expense')
      .reduce((sum, t) => sum + t.amount, 0),
    todayTransactionCount: todayTransactions.length
  };
};

/**
 * 根据角色设置生成初始资金
 * 会根据AI的性格描述推断职业和收入水平
 */
export const generateInitialBalance = (characterSettings?: any): number => {
  if (!characterSettings) return 5000; // 默认5000元
  
  const personality = (characterSettings.personality || '').toLowerCase();
  
  // 高收入职业关键词
  const highIncomeKeywords = ['总裁', 'ceo', '老板', '企业家', '医生', '律师', '投资', '金融'];
  // 中等收入职业关键词
  const middleIncomeKeywords = ['白领', '工程师', '程序员', '设计师', '老师', '教师', '公务员'];
  // 学生或低收入关键词
  const studentKeywords = ['学生', '实习', '兼职'];
  
  // 检查关键词
  for (const keyword of highIncomeKeywords) {
    if (personality.includes(keyword)) {
      return Math.floor(Math.random() * 500000) + 100000; // 10万-60万
    }
  }
  
  for (const keyword of middleIncomeKeywords) {
    if (personality.includes(keyword)) {
      return Math.floor(Math.random() * 50000) + 10000; // 1万-6万
    }
  }
  
  for (const keyword of studentKeywords) {
    if (personality.includes(keyword)) {
      return Math.floor(Math.random() * 3000) + 1000; // 1000-4000
    }
  }
  
  // 默认中等收入
  return Math.floor(Math.random() * 30000) + 5000; // 5000-35000
};

/**
 * 为AI设置自动收入
 * 根据角色设置配置定期收入（如工资、兼职收入等）
 */
export const setupAutoIncome = async (aiId: string, characterSettings?: any): Promise<void> => {
  if (!characterSettings) return;
  
  const financeData = await getAIFinanceData(aiId);
  const personality = (characterSettings.personality || '').toLowerCase();
  
  // 根据角色推断收入配置
  const incomeConfigs: IncomeConfig[] = [];
  
  // 检测是否有工作
  if (personality.includes('总裁') || personality.includes('ceo') || personality.includes('老板')) {
    incomeConfigs.push({
      enabled: true,
      baseAmount: 75000, // 基础7.5万
      randomRange: [50000, 100000], // 5万-10万/月
      frequency: 'monthly',
      description: '公司分红',
      lastIncomeTime: Date.now(),
      nextIncomeTime: Date.now() + 30 * 24 * 60 * 60 * 1000 // 30天后
    });
  } else if (personality.includes('白领') || personality.includes('工程师') || personality.includes('程序员')) {
    incomeConfigs.push({
      enabled: true,
      baseAmount: 10000, // 基础1万
      randomRange: [5000, 15000], // 5000-15000/月
      frequency: 'monthly',
      description: '工资',
      lastIncomeTime: Date.now(),
      nextIncomeTime: Date.now() + 30 * 24 * 60 * 60 * 1000
    });
  } else if (personality.includes('学生')) {
    incomeConfigs.push({
      enabled: true,
      baseAmount: 1500, // 基础1500
      randomRange: [500, 2500], // 500-2500
      frequency: 'weekly',
      description: '兼职收入',
      lastIncomeTime: Date.now(),
      nextIncomeTime: Date.now() + 7 * 24 * 60 * 60 * 1000 // 7天后
    });
  }
  
  financeData.incomeConfigs = incomeConfigs;
  await updateAIFinanceData(financeData);
};

/**
 * 生成随机日常支出
 * 模拟AI的日常消费行为
 */
export const generateDailyExpense = async (aiId: string, characterSettings?: any): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  
  // 检查余额
  if (financeData.balance < 50) return; // 余额太低不消费
  
  const personality = (characterSettings?.personality || '').toLowerCase();
  
  // 随机决定是否消费（30%概率）
  if (Math.random() > 0.3) return;
  
  // 消费类型和金额范围
  const expenseTypes = [
    { category: 'shopping', description: '购买日用品', minAmount: 20, maxAmount: 200 },
    { category: 'shopping', description: '网购', minAmount: 50, maxAmount: 500 },
    { category: 'other', description: '餐饮', minAmount: 15, maxAmount: 100 },
    { category: 'other', description: '交通', minAmount: 5, maxAmount: 50 },
    { category: 'other', description: '娱乐', minAmount: 30, maxAmount: 300 }
  ];
  
  // 根据身份调整消费水平
  let multiplier = 1;
  if (personality.includes('总裁') || personality.includes('老板')) {
    multiplier = 3;
  } else if (personality.includes('学生')) {
    multiplier = 0.5;
  }
  
  // 随机选择消费类型
  const expenseType = expenseTypes[Math.floor(Math.random() * expenseTypes.length)];
  const amount = Math.floor((Math.random() * (expenseType.maxAmount - expenseType.minAmount) + expenseType.minAmount) * multiplier);
  
  // 确保不超过余额
  const finalAmount = Math.min(amount, financeData.balance * 0.1); // 最多花10%的余额
  
  if (finalAmount >= 5) { // 至少5元才记录
    await addTransaction(
      aiId,
      'expense',
      finalAmount,
      expenseType.category,
      expenseType.description,
      undefined,
      undefined,
      true // 自动生成
    );
  }
};
