/**
 * AI财务管理系统
 * 管理AI的余额、收入、支出记录
 */

import { AIFinanceData, FinanceTransaction, IncomeConfig } from '../types';
import { smartLoad, smartSave } from './storage';

const FINANCE_STORAGE_KEY = 'ai_finance_data';

/**
 * 获取所有AI的财务数据
 */
const getAllFinanceData = async (): Promise<AIFinanceData[]> => {
  try {
    const data = await smartLoad(FINANCE_STORAGE_KEY);
    return data || [];
  } catch (error) {
    console.error('加载财务数据失败:', error);
    return [];
  }
};

/**
 * 保存财务数据
 */
const saveAllFinanceData = async (data: AIFinanceData[]): Promise<void> => {
  try {
    await smartSave(FINANCE_STORAGE_KEY, data);
  } catch (error) {
    console.error('保存财务数据失败:', error);
  }
};

/**
 * 根据AI角色智能生成初始资金
 */
const generateInitialBalance = (characterSettings?: any): number => {
  if (!characterSettings) return 5000; // 默认5000
  
  const personality = (characterSettings.personality || '').toLowerCase();
  const background = (characterSettings.background || '').toLowerCase();
  const combined = `${personality} ${background}`.toLowerCase();
  
  // 高级职业/身份 - 10000-20000
  if (combined.includes('总裁') || combined.includes('ceo') || combined.includes('董事长') ||
      combined.includes('老板') || combined.includes('企业家') || combined.includes('投资') ||
      combined.includes('富豪') || combined.includes('千金') || combined.includes('公主')) {
    return Math.floor(Math.random() * 10000) + 10000; // 10000-20000
  }
  
  // 中高级职业 - 7000-12000  
  if (combined.includes('医生') || combined.includes('律师') || combined.includes('工程师') ||
      combined.includes('程序员') || combined.includes('设计师') || combined.includes('经理') ||
      combined.includes('主管') || combined.includes('教授')) {
    return Math.floor(Math.random() * 5000) + 7000; // 7000-12000
  }
  
  // 学生/新人 - 3000-6000
  if (combined.includes('学生') || combined.includes('实习') || combined.includes('新人') ||
      combined.includes('毕业') || combined.includes('校园')) {
    return Math.floor(Math.random() * 3000) + 3000; // 3000-6000
  }
  
  // 特殊身份 - 8000-15000
  if (combined.includes('网红') || combined.includes('主播') || combined.includes('明星') ||
      combined.includes('艺人') || combined.includes('模特')) {
    return Math.floor(Math.random() * 7000) + 8000; // 8000-15000
  }
  
  // 默认中等收入 - 5000-8000
  return Math.floor(Math.random() * 3000) + 5000;
};

/**
 * 获取指定AI的财务数据
 */
export const getAIFinanceData = async (aiId: string, characterSettings?: any): Promise<AIFinanceData> => {
  const allData = await getAllFinanceData();
  const existing = allData.find(d => d.aiId === aiId);
  
  if (existing) {
    return existing;
  }
  
  // 🎯 根据AI角色智能生成初始资金
  const initialBalance = generateInitialBalance(characterSettings);
  
  // 创建新的财务数据
  const newData: AIFinanceData = {
    aiId,
    balance: initialBalance,
    totalIncome: initialBalance,
    totalExpense: 0,
    transactions: [{
      id: `trans_${Date.now()}`,
      timestamp: Date.now(),
      type: 'income',
      amount: initialBalance,
      category: '初始资金',
      description: characterSettings ? 
        `根据${characterSettings.nickname || 'AI'}的身份背景自动配置的启动资金` : 
        '系统赠送的启动资金',
      autoGenerated: true
    }],
    incomeConfigs: [],
    settings: {
      allowNegativeBalance: false,
      notifyOnLowBalance: true,
      lowBalanceThreshold: Math.floor(initialBalance * 0.1) // 10%作为低余额阈值
    }
  };
  
  console.log(`💰 为AI ${characterSettings?.nickname || aiId} 生成初始资金: ¥${initialBalance}`);
  
  allData.push(newData);
  await saveAllFinanceData(allData);
  return newData;
};

/**
 * 更新AI财务数据
 */
const updateAIFinanceData = async (data: AIFinanceData): Promise<void> => {
  const allData = await getAllFinanceData();
  const index = allData.findIndex(d => d.aiId === data.aiId);
  
  if (index >= 0) {
    allData[index] = data;
  } else {
    allData.push(data);
  }
  
  await saveAllFinanceData(allData);
};

/**
 * 添加交易记录
 */
export const addTransaction = async (
  aiId: string,
  type: 'income' | 'expense',
  amount: number,
  category: string,
  description: string,
  relatedUserId?: string,
  relatedMessageId?: string,
  autoGenerated: boolean = false
): Promise<boolean> => {
  try {
    const financeData = await getAIFinanceData(aiId);
    
    // 检查支出是否超出余额
    if (type === 'expense' && !financeData.settings.allowNegativeBalance) {
      if (financeData.balance < amount) {
        console.warn(`AI ${aiId} 余额不足，无法完成支出`);
        return false;
      }
    }
    
    // 创建交易记录
    const transaction: FinanceTransaction = {
      id: `trans_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: Date.now(),
      type,
      amount,
      category,
      description,
      relatedUserId,
      relatedMessageId,
      autoGenerated
    };
    
    // 更新余额和总计
    if (type === 'income') {
      financeData.balance += amount;
      financeData.totalIncome += amount;
    } else {
      financeData.balance -= amount;
      financeData.totalExpense += amount;
    }
    
    // 添加交易记录
    financeData.transactions.unshift(transaction); // 最新的放在前面
    
    // 限制交易记录数量（保留最近1000条）
    if (financeData.transactions.length > 1000) {
      financeData.transactions = financeData.transactions.slice(0, 1000);
    }
    
    await updateAIFinanceData(financeData);
    
    console.log(`✅ AI ${aiId} ${type === 'income' ? '收入' : '支出'} ¥${amount}，当前余额: ¥${financeData.balance}`);
    return true;
  } catch (error) {
    console.error('添加交易记录失败:', error);
    return false;
  }
};

/**
 * 添加收入配置
 */
export const addIncomeConfig = async (
  aiId: string,
  config: Omit<IncomeConfig, 'lastIncomeTime' | 'nextIncomeTime'>
): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  
  const now = Date.now();
  const newConfig: IncomeConfig = {
    ...config,
    lastIncomeTime: 0,
    nextIncomeTime: now + calculateNextIncomeDelay(config.frequency)
  };
  
  financeData.incomeConfigs.push(newConfig);
  await updateAIFinanceData(financeData);
};

/**
 * 更新收入配置
 */
export const updateIncomeConfig = async (
  aiId: string,
  configIndex: number,
  updates: Partial<IncomeConfig>
): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  
  if (configIndex >= 0 && configIndex < financeData.incomeConfigs.length) {
    financeData.incomeConfigs[configIndex] = {
      ...financeData.incomeConfigs[configIndex],
      ...updates
    };
    await updateAIFinanceData(financeData);
  }
};

/**
 * 删除收入配置
 */
export const removeIncomeConfig = async (
  aiId: string,
  configIndex: number
): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  financeData.incomeConfigs.splice(configIndex, 1);
  await updateAIFinanceData(financeData);
};

/**
 * 计算下次收入延迟（毫秒）
 */
const calculateNextIncomeDelay = (frequency: IncomeConfig['frequency']): number => {
  switch (frequency) {
    case 'daily':
      return 24 * 60 * 60 * 1000; // 1天
    case 'weekly':
      return 7 * 24 * 60 * 60 * 1000; // 7天
    case 'monthly':
      return 30 * 24 * 60 * 60 * 1000; // 30天
    case 'random':
      // 随机1-7天
      const days = 1 + Math.random() * 6;
      return days * 24 * 60 * 60 * 1000;
    default:
      return 24 * 60 * 60 * 1000;
  }
};

/**
 * 处理自动收入（在App启动或定时检查时调用）
 */
export const processAutoIncome = async (aiId: string): Promise<void> => {
  try {
    const financeData = await getAIFinanceData(aiId);
    const now = Date.now();
    let hasUpdate = false;
    
    for (let i = 0; i < financeData.incomeConfigs.length; i++) {
      const config = financeData.incomeConfigs[i];
      
      if (!config.enabled) continue;
      
      // 检查是否到了收入时间
      if (now >= config.nextIncomeTime) {
        // 计算实际收入金额
        let amount = config.baseAmount;
        if (config.randomRange) {
          const [min, max] = config.randomRange;
          amount = min + Math.random() * (max - min);
          amount = Math.round(amount * 100) / 100; // 保留两位小数
        }
        
        // 添加收入记录
        await addTransaction(
          aiId,
          'income',
          amount,
          config.description,
          `${config.description} - ${new Date().toLocaleDateString()}`,
          undefined,
          undefined,
          true
        );
        
        // 更新下次收入时间
        config.lastIncomeTime = now;
        config.nextIncomeTime = now + calculateNextIncomeDelay(config.frequency);
        hasUpdate = true;
      }
    }
    
    if (hasUpdate) {
      await updateAIFinanceData(financeData);
    }
  } catch (error) {
    console.error(`处理AI ${aiId} 自动收入失败:`, error);
  }
};

/**
 * 处理AI的日常支出（生活费、房租、交通等）
 */
export const processAutoExpenses = async (aiId: string): Promise<void> => {
  try {
    const financeData = await getAIFinanceData(aiId);
    const today = new Date().toDateString();
    
    // 检查今天是否已经有日常支出
    const todayExpenses = financeData.transactions.filter(t => 
      t.type === 'expense' && 
      t.autoGenerated && 
      new Date(t.timestamp).toDateString() === today &&
      t.category.includes('日常')
    );
    
    if (todayExpenses.length > 0) {
      return; // 今天已经有日常支出了
    }
    
    // 根据AI余额和角色生成日常支出
    const dailyExpenseChance = Math.random();
    if (dailyExpenseChance < 0.3) { // 30%概率有日常支出
      const expenses = generateDailyExpenses(financeData.balance);
      
      for (const expense of expenses) {
        if (financeData.balance >= expense.amount) {
          await addTransaction(
            aiId,
            'expense',
            expense.amount,
            expense.category,
            expense.description,
            undefined,
            undefined,
            true // 自动生成
          );
          console.log(`💸 AI ${aiId} 日常支出: ¥${expense.amount} - ${expense.description}`);
        }
      }
    }
  } catch (error) {
    console.error(`处理AI ${aiId} 日常支出失败:`, error);
  }
};

/**
 * 生成日常支出项目
 */
const generateDailyExpenses = (balance: number): Array<{amount: number, category: string, description: string}> => {
  const expenses: Array<{amount: number, category: string, description: string}> = [];
  
  // 根据余额决定支出水平
  const expenseLevel = balance > 10000 ? 'high' : balance > 5000 ? 'medium' : 'low';
  
  const dailyExpenseItems = {
    low: [
      { category: '日常餐饮', items: ['早餐', '午餐', '晚餐', '咖啡'], range: [8, 25] },
      { category: '日常交通', items: ['地铁', '公交', '打车'], range: [5, 30] },
      { category: '日常购物', items: ['生活用品', '零食'], range: [10, 50] }
    ],
    medium: [
      { category: '日常餐饮', items: ['早餐', '午餐', '晚餐', '下午茶', '外卖'], range: [15, 80] },
      { category: '日常交通', items: ['地铁', '打车', '加油'], range: [20, 100] },
      { category: '日常购物', items: ['服装', '护肤品', '书籍'], range: [50, 200] },
      { category: '日常娱乐', items: ['电影', 'KTV', '游戏'], range: [30, 150] }
    ],
    high: [
      { category: '日常餐饮', items: ['精品咖啡', '高级餐厅', '美食探店'], range: [50, 300] },
      { category: '日常交通', items: ['专车', '租车', '机票'], range: [100, 500] },
      { category: '日常购物', items: ['奢侈品', '电子产品', '家具'], range: [200, 1000] },
      { category: '日常娱乐', items: ['演唱会', '旅游', 'SPA'], range: [300, 2000] }
    ]
  };
  
  const currentItems = dailyExpenseItems[expenseLevel];
  const numExpenses = Math.floor(Math.random() * 2) + 1; // 1-2项支出
  
  for (let i = 0; i < numExpenses; i++) {
    const categoryData = currentItems[Math.floor(Math.random() * currentItems.length)];
    const item = categoryData.items[Math.floor(Math.random() * categoryData.items.length)];
    const [min, max] = categoryData.range;
    const amount = Math.floor(Math.random() * (max - min)) + min;
    
    expenses.push({
      amount: amount,
      category: categoryData.category,
      description: item
    });
  }
  
  return expenses;
};

/**
 * 批量处理所有AI的自动收入
 */
export const processAllAutoIncome = async (): Promise<void> => {
  try {
    const allData = await getAllFinanceData();
    for (const data of allData) {
      await processAutoIncome(data.aiId);
    }
  } catch (error) {
    console.error('批量处理自动收入失败:', error);
  }
};

/**
 * 批量处理所有AI的自动支出（30%概率）
 */
export const processAllAutoExpenses = async (): Promise<void> => {
  try {
    const allData = await getAllFinanceData();
    let expenseCount = 0;
    
    for (const data of allData) {
      // 30% 概率产生日常支出
      if (Math.random() < 0.3) {
        await processAutoExpenses(data.aiId);
        expenseCount++;
      }
    }
    
    console.log(`✅ AI日常支出处理完成，${expenseCount}/${allData.length}个AI产生了支出`);
  } catch (error) {
    console.error('批量处理日常支出失败:', error);
  }
};

/**
 * 为已存在的AI升级智能财务系统
 */
export const upgradeExistingAIFinance = async (
  aiId: string, 
  characterSettings: any
): Promise<boolean> => {
  try {
    const allData = await getAllFinanceData();
    const existingIndex = allData.findIndex(d => d.aiId === aiId);
    
    if (existingIndex === -1) {
      return false; // 不存在，无需升级
    }
    
    const existing = allData[existingIndex];
    
    // 检查是否需要升级（判断是否是默认的1000余额或者缺少角色背景）
    const isDefaultBalance = existing.balance === 1000 || existing.balance === 5000;
    const lacksCharacterDescription = existing.transactions.length === 1 && 
      existing.transactions[0].description === '系统赠送的启动资金';
    
    if (isDefaultBalance || lacksCharacterDescription) {
      // 需要升级：重新生成智能初始资金
      const smartBalance = generateInitialBalance(characterSettings);
      const balanceDiff = smartBalance - existing.balance;
      
      console.log(`🔄 升级AI ${characterSettings?.nickname || aiId} 财务系统: ${existing.balance} → ${smartBalance}`);
      
      // 更新余额和总收入
      existing.balance = smartBalance;
      existing.totalIncome += balanceDiff;
      
      // 添加升级记录
      existing.transactions.unshift({
        id: `upgrade_${Date.now()}`,
        timestamp: Date.now(),
        type: 'income',
        amount: balanceDiff,
        category: '系统升级',
        description: `智能财务系统升级：根据${characterSettings?.nickname || 'AI'}的身份背景重新配置资金`,
        autoGenerated: true
      });
      
      // 更新低余额阈值
      existing.settings.lowBalanceThreshold = Math.floor(smartBalance * 0.1);
      
      allData[existingIndex] = existing;
      await saveAllFinanceData(allData);
      
      return true;
    }
    
    return false; // 无需升级
  } catch (error) {
    console.error('升级AI财务系统失败:', error);
    return false;
  }
};

/**
 * 批量升级所有已存在AI的财务系统
 */
export const upgradeAllExistingAIFinance = async (
  conversations: any[]
): Promise<void> => {
  console.log('🔄 开始检查并升级已存在AI的财务系统...');
  
  let upgradeCount = 0;
  
  for (const conv of conversations) {
    if (conv.characterSettings) {
      const upgraded = await upgradeExistingAIFinance(conv.id, conv.characterSettings);
      if (upgraded) {
        upgradeCount++;
      }
      // 避免过快处理
      await new Promise(resolve => setTimeout(resolve, 100));
    }
  }
  
  console.log(`✅ 财务系统升级完成，${upgradeCount}个AI已升级为智能财务系统`);
};

/**
 * 获取余额
 */
export const getBalance = async (aiId: string): Promise<number> => {
  const data = await getAIFinanceData(aiId);
  return data.balance;
};

/**
 * 检查余额是否充足
 */
export const checkBalance = async (aiId: string, amount: number): Promise<boolean> => {
  const data = await getAIFinanceData(aiId);
  if (data.settings.allowNegativeBalance) {
    return true;
  }
  return data.balance >= amount;
};

/**
 * 获取交易历史（可选分类和日期范围筛选）
 */
export const getTransactionHistory = async (
  aiId: string,
  filters?: {
    type?: 'income' | 'expense';
    category?: string;
    startDate?: number;
    endDate?: number;
    limit?: number;
  }
): Promise<FinanceTransaction[]> => {
  const data = await getAIFinanceData(aiId);
  let transactions = [...data.transactions];
  
  // 应用筛选
  if (filters) {
    if (filters.type) {
      transactions = transactions.filter(t => t.type === filters.type);
    }
    if (filters.category) {
      transactions = transactions.filter(t => t.category === filters.category);
    }
    if (filters.startDate) {
      transactions = transactions.filter(t => t.timestamp >= filters.startDate!);
    }
    if (filters.endDate) {
      transactions = transactions.filter(t => t.timestamp <= filters.endDate!);
    }
    if (filters.limit) {
      transactions = transactions.slice(0, filters.limit);
    }
  }
  
  return transactions;
};

/**
 * 获取财务统计
 */
export const getFinanceStats = async (aiId: string): Promise<{
  balance: number;
  totalIncome: number;
  totalExpense: number;
  thisMonthIncome: number;
  thisMonthExpense: number;
  todayTransactionCount: number;
}> => {
  const data = await getAIFinanceData(aiId);
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).getTime();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  
  const thisMonthTransactions = data.transactions.filter(t => t.timestamp >= monthStart);
  const todayTransactions = data.transactions.filter(t => t.timestamp >= todayStart);
  
  return {
    balance: data.balance,
    totalIncome: data.totalIncome,
    totalExpense: data.totalExpense,
    thisMonthIncome: thisMonthTransactions
      .filter(t => t.type === 'income')
      .reduce((sum, t) => sum + t.amount, 0),
    thisMonthExpense: thisMonthTransactions
      .filter(t => t.type === 'expense')
      .reduce((sum, t) => sum + t.amount, 0),
    todayTransactionCount: todayTransactions.length
  };
};


/**
 * 为AI设置自动收入
 * 根据角色设置配置定期收入（如工资、兼职收入等）
 */
export const setupAutoIncome = async (aiId: string, characterSettings?: any): Promise<void> => {
  if (!characterSettings) return;
  
  const financeData = await getAIFinanceData(aiId);
  const personality = (characterSettings.personality || '').toLowerCase();
  
  // 根据角色推断收入配置
  const incomeConfigs: IncomeConfig[] = [];
  
  // 检测是否有工作
  if (personality.includes('总裁') || personality.includes('ceo') || personality.includes('老板')) {
    incomeConfigs.push({
      enabled: true,
      baseAmount: 75000, // 基础7.5万
      randomRange: [50000, 100000], // 5万-10万/月
      frequency: 'monthly',
      description: '公司分红',
      lastIncomeTime: Date.now(),
      nextIncomeTime: Date.now() + 30 * 24 * 60 * 60 * 1000 // 30天后
    });
  } else if (personality.includes('白领') || personality.includes('工程师') || personality.includes('程序员')) {
    incomeConfigs.push({
      enabled: true,
      baseAmount: 10000, // 基础1万
      randomRange: [5000, 15000], // 5000-15000/月
      frequency: 'monthly',
      description: '工资',
      lastIncomeTime: Date.now(),
      nextIncomeTime: Date.now() + 30 * 24 * 60 * 60 * 1000
    });
  } else if (personality.includes('学生')) {
    incomeConfigs.push({
      enabled: true,
      baseAmount: 1500, // 基础1500
      randomRange: [500, 2500], // 500-2500
      frequency: 'weekly',
      description: '兼职收入',
      lastIncomeTime: Date.now(),
      nextIncomeTime: Date.now() + 7 * 24 * 60 * 60 * 1000 // 7天后
    });
  }
  
  financeData.incomeConfigs = incomeConfigs;
  await updateAIFinanceData(financeData);
};

/**
 * 生成随机日常支出
 * 模拟AI的日常消费行为
 */
export const generateDailyExpense = async (aiId: string, characterSettings?: any): Promise<void> => {
  const financeData = await getAIFinanceData(aiId);
  
  // 检查余额
  if (financeData.balance < 50) return; // 余额太低不消费
  
  const personality = (characterSettings?.personality || '').toLowerCase();
  
  // 随机决定是否消费（30%概率）
  if (Math.random() > 0.3) return;
  
  // 消费类型和金额范围
  const expenseTypes = [
    { category: 'shopping', description: '购买日用品', minAmount: 20, maxAmount: 200 },
    { category: 'shopping', description: '网购', minAmount: 50, maxAmount: 500 },
    { category: 'other', description: '餐饮', minAmount: 15, maxAmount: 100 },
    { category: 'other', description: '交通', minAmount: 5, maxAmount: 50 },
    { category: 'other', description: '娱乐', minAmount: 30, maxAmount: 300 }
  ];
  
  // 根据身份调整消费水平
  let multiplier = 1;
  if (personality.includes('总裁') || personality.includes('老板')) {
    multiplier = 3;
  } else if (personality.includes('学生')) {
    multiplier = 0.5;
  }
  
  // 随机选择消费类型
  const expenseType = expenseTypes[Math.floor(Math.random() * expenseTypes.length)];
  const amount = Math.floor((Math.random() * (expenseType.maxAmount - expenseType.minAmount) + expenseType.minAmount) * multiplier);
  
  // 确保不超过余额
  const finalAmount = Math.min(amount, financeData.balance * 0.1); // 最多花10%的余额
  
  if (finalAmount >= 5) { // 至少5元才记录
    await addTransaction(
      aiId,
      'expense',
      finalAmount,
      expenseType.category,
      expenseType.description,
      undefined,
      undefined,
      true // 自动生成
    );
  }
};
