import { smartLoad, smartSave } from './storage';

export interface MemoryEntry {
  id: string;
  timestamp: number;
  content: string;
  importance: 'low' | 'medium' | 'high';
  category?: string;
  relatedMessageIds?: string[];
  autoGenerated: boolean;
}

export interface MemoryBank {
  contactId: string;
  memories: MemoryEntry[];
  lastSummaryMessageCount: number;
  totalMessagesSinceLastSummary: number;
  settings: {
    autoSummaryInterval: number;
    maxMemories: number;
    enableAutoSummary: boolean;
  };
}

const MEMORY_STORAGE_KEY = 'chat_memory_banks';

/**
 * 获取联系人的记忆库
 */
export const getMemoryBank = async (contactId: string): Promise<MemoryBank> => {
  const banks = await getAllMemoryBanks();
  const existing = banks.find(b => b.contactId === contactId);
  
  if (existing) {
    return existing;
  }
  
  // 创建新的记忆库
  const newBank: MemoryBank = {
    contactId,
    memories: [],
    lastSummaryMessageCount: 0,
    totalMessagesSinceLastSummary: 0,
    settings: {
      autoSummaryInterval: 25,
      maxMemories: 100,
      enableAutoSummary: true
    }
  };
  
  await saveMemoryBank(newBank);
  return newBank;
};

/**
 * 获取所有记忆库
 */
const getAllMemoryBanks = async (): Promise<MemoryBank[]> => {
  try {
    const stored = await smartLoad(MEMORY_STORAGE_KEY);
    return stored || [];
  } catch (error) {
    console.error('加载记忆库失败:', error);
    return [];
  }
};

/**
 * 保存记忆库
 */
export const saveMemoryBank = async (bank: MemoryBank): Promise<void> => {
  try {
    const banks = await getAllMemoryBanks();
    const index = banks.findIndex(b => b.contactId === bank.contactId);
    
    if (index >= 0) {
      banks[index] = bank;
    } else {
      banks.push(bank);
    }
    
    await smartSave(MEMORY_STORAGE_KEY, banks);
  } catch (error) {
    console.error('保存记忆库失败:', error);
  }
};

/**
 * 添加记忆条目
 */
export const addMemory = async (
  contactId: string,
  content: string,
  importance: 'low' | 'medium' | 'high' = 'medium',
  category?: string,
  autoGenerated: boolean = false
): Promise<MemoryEntry> => {
  const bank = await getMemoryBank(contactId);
  
  const newMemory: MemoryEntry = {
    id: `memory_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    timestamp: Date.now(),
    content,
    importance,
    category,
    autoGenerated
  };
  
  bank.memories.unshift(newMemory);
  
  // 如果超过最大记忆数，删除最旧的低重要性记忆
  if (bank.memories.length > bank.settings.maxMemories) {
    const lowImportance = bank.memories.filter(m => m.importance === 'low');
    if (lowImportance.length > 0) {
      const toDelete = lowImportance[lowImportance.length - 1];
      bank.memories = bank.memories.filter(m => m.id !== toDelete.id);
    } else {
      const mediumImportance = bank.memories.filter(m => m.importance === 'medium');
      if (mediumImportance.length > 0) {
        const toDelete = mediumImportance[mediumImportance.length - 1];
        bank.memories = bank.memories.filter(m => m.id !== toDelete.id);
      } else {
        bank.memories.pop();
      }
    }
  }
  
  await saveMemoryBank(bank);
  return newMemory;
};

/**
 * 删除记忆
 */
export const deleteMemory = async (contactId: string, memoryId: string): Promise<void> => {
  const bank = await getMemoryBank(contactId);
  bank.memories = bank.memories.filter(m => m.id !== memoryId);
  await saveMemoryBank(bank);
};

/**
 * 更新记忆的重要性
 */
export const updateMemoryImportance = async (
  contactId: string,
  memoryId: string,
  importance: 'low' | 'medium' | 'high'
): Promise<void> => {
  const bank = await getMemoryBank(contactId);
  const memory = bank.memories.find(m => m.id === memoryId);
  if (memory) {
    memory.importance = importance;
    await saveMemoryBank(bank);
  }
};

/**
 * 清空联系人的所有记忆
 */
export const clearMemoryBank = async (contactId: string): Promise<void> => {
  const bank = await getMemoryBank(contactId);
  bank.memories = [];
  bank.lastSummaryMessageCount = 0;
  bank.totalMessagesSinceLastSummary = 0;
  await saveMemoryBank(bank);
};

/**
 * 更新记忆库设置
 */
export const updateMemorySettings = async (
  contactId: string,
  settings: Partial<MemoryBank['settings']>
): Promise<void> => {
  const bank = await getMemoryBank(contactId);
  bank.settings = { ...bank.settings, ...settings };
  await saveMemoryBank(bank);
};

/**
 * 检查是否需要自动总结
 */
export const shouldTriggerAutoSummary = async (contactId: string, currentMessageCount: number): Promise<boolean> => {
  const bank = await getMemoryBank(contactId);
  
  if (!bank.settings.enableAutoSummary) {
    return false;
  }
  
  const messagesSinceLastSummary = currentMessageCount - bank.lastSummaryMessageCount;
  return messagesSinceLastSummary >= bank.settings.autoSummaryInterval;
};

/**
 * 更新总结计数器
 */
export const updateSummaryCounter = async (contactId: string, currentMessageCount: number): Promise<void> => {
  const bank = await getMemoryBank(contactId);
  bank.lastSummaryMessageCount = currentMessageCount;
  bank.totalMessagesSinceLastSummary = 0;
  await saveMemoryBank(bank);
};

/**
 * 构建记忆上下文（用于AI回复时）
 */
export const buildMemoryContext = (memories: MemoryEntry[]): string => {
  if (memories.length === 0) {
    return '';
  }
  
  // 按重要性和时间排序
  const sortedMemories = [...memories].sort((a, b) => {
    const importanceWeight = { high: 3, medium: 2, low: 1 };
    const weightDiff = importanceWeight[b.importance] - importanceWeight[a.importance];
    if (weightDiff !== 0) return weightDiff;
    return b.timestamp - a.timestamp;
  });
  
  // 取最重要的前20条
  const topMemories = sortedMemories.slice(0, 20);
  
  let context = '\n【长期记忆库】\n';
  context += '以下是你和这位用户长期交往积累的记忆，请自然地运用这些记忆。\n\n';
  
  // 按分类整理
  const categories: Record<string, MemoryEntry[]> = {};
  topMemories.forEach(m => {
    const cat = m.category || '其他';
    if (!categories[cat]) {
      categories[cat] = [];
    }
    categories[cat].push(m);
  });
  
  // 输出记忆
  Object.entries(categories).forEach(([category, mems]) => {
    context += `【${category}】\n`;
    mems.forEach(m => {
      const importance = m.importance === 'high' ? '⭐⭐⭐' : m.importance === 'medium' ? '⭐⭐' : '⭐';
      context += `${importance} ${m.content}\n`;
    });
    context += '\n';
  });
  
  context += '**重要提示**：\n';
  context += '- 这些记忆是你和用户长期交往积累的，请自然地运用\n';
  context += '- 保持一致性：你的观点、喜好、经历要与记忆保持一致\n';
  context += '- 不要刻意展示记忆，而是在合适的时候自然提起\n';
  context += '- 避免重复询问你已经知道的信息\n';
  
  return context;
};

/**
 * 生成记忆总结提示词
 */
export const buildMemorySummaryPrompt = (messages: any[], existingMemories: MemoryEntry[]): string => {
  // 提取最近的对话内容
  const recentMessages = messages.slice(-30);
  
  let conversationText = '';
  recentMessages.forEach(msg => {
    const speaker = msg.role === 'user' ? '用户' : 'AI';
    conversationText += `${speaker}: ${msg.content}\n`;
  });
  
  const existingMemoriesText = existingMemories.length > 0
    ? '\n\n【已有记忆】\n' + existingMemories.map(m => `- [${m.category || '其他'}] ${m.content}`).join('\n')
    : '';
  
  return `
【记忆总结任务】

请仔细分析以下对话，提取值得长期记忆的关键信息。

${existingMemoriesText}

【最近对话内容】
${conversationText}

【任务要求】
1. 提取以下类型的重要信息（如果有）：

**关于用户的记忆：**
   - 个人信息：用户的姓名、年龄、职业、家庭情况等
   - 喜好偏好：用户喜欢/不喜欢什么
   - 重要事件：用户提到的重要经历、计划、目标
   - 人际关系：用户提到的家人、朋友等
   - 生活习惯：作息时间、日常习惯等
   - 情感状态：用户的情绪、压力、困扰等

**关于AI角色自己的记忆：**
   - AI提到的自己的经历和故事
   - AI表达的观点、态度、喜好
   - AI提到的自己的人际关系
   - AI分享的个人感受和情绪

**对话互动记忆：**
   - 重要的对话片段
   - 共同的话题和讨论
   - 有趣的互动和玩笑
   - 承诺和约定

2. 每条记忆要求：
   - 简洁明确，一句话说清楚
   - 避免重复已有记忆
   - 只记录确定的信息，不要推测

3. 重要性判断：
   - HIGH（高）：非常重要的信息、重大事件、核心喜好
   - MEDIUM（中）：一般性信息、日常事件
   - LOW（低）：次要信息、可有可无的细节

【输出格式】
请严格按照以下JSON格式输出：
{
  "memories": [
    {
      "content": "记忆内容",
      "importance": "HIGH|MEDIUM|LOW",
      "category": "个人信息|喜好|事件|关系|习惯|情感|AI经历|AI观点|对话互动|其他"
    }
  ]
}

如果没有值得记忆的新信息，返回：
{
  "memories": []
}
`;
};

/**
 * 解析AI返回的记忆总结
 */
export const parseMemorySummaryResponse = (response: string): Array<{
  content: string;
  importance: 'low' | 'medium' | 'high';
  category?: string;
}> => {
  try {
    // 尝试提取JSON部分
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.warn('未找到JSON格式的记忆总结');
      return [];
    }
    
    const parsed = JSON.parse(jsonMatch[0]);
    
    if (!parsed.memories || !Array.isArray(parsed.memories)) {
      return [];
    }
    
    return parsed.memories.map((m: any) => ({
      content: m.content,
      importance: (m.importance === 'HIGH' ? 'high' : m.importance === 'LOW' ? 'low' : 'medium') as 'low' | 'medium' | 'high',
      category: m.category
    }));
  } catch (error) {
    console.error('解析记忆总结失败:', error);
    return [];
  }
};
