/**
 * AI长期记忆系统
 * 实现自动总结和记忆管理
 */

import { MemoryBank, MemoryEntry, Message } from '../types';

// 重新导出类型以便其他组件使用
export type { MemoryEntry };

const MEMORY_STORAGE_KEY = 'chat_memory_banks';

/**
 * 获取对话的记忆库
 */
export const getMemoryBank = (conversationId: string): MemoryBank => {
  const banks = getAllMemoryBanks();
  const existing = banks.find(b => b.conversationId === conversationId);
  
  if (existing) {
    return existing;
  }
  
  // 创建新的记忆库
  const newBank: MemoryBank = {
    conversationId,
    memories: [],
    lastSummaryMessageCount: 0,
    totalMessagesSinceLastSummary: 0,
    settings: {
      autoSummaryInterval: 25, // 每25条消息自动总结一次
      maxMemories: 100, // 最多保存100条记忆
      enableAutoSummary: true
    }
  };
  
  saveMemoryBank(newBank);
  return newBank;
};

/**
 * 获取所有记忆库
 */
const getAllMemoryBanks = (): MemoryBank[] => {
  try {
    const stored = localStorage.getItem(MEMORY_STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch (error) {
    console.error('Failed to load memory banks:', error);
    return [];
  }
};

/**
 * 保存记忆库
 */
export const saveMemoryBank = (bank: MemoryBank): void => {
  try {
    const banks = getAllMemoryBanks();
    const index = banks.findIndex(b => b.conversationId === bank.conversationId);
    
    if (index >= 0) {
      banks[index] = bank;
    } else {
      banks.push(bank);
    }
    
    localStorage.setItem(MEMORY_STORAGE_KEY, JSON.stringify(banks));
  } catch (error) {
    console.error('Failed to save memory bank:', error);
  }
};

/**
 * 添加记忆条目
 */
export const addMemory = (
  conversationId: string,
  content: string,
  importance: 'low' | 'medium' | 'high' = 'medium',
  category?: string,
  autoGenerated: boolean = false
): MemoryEntry => {
  const bank = getMemoryBank(conversationId);
  
  const newMemory: MemoryEntry = {
    id: `memory_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    timestamp: Date.now(),
    content,
    importance,
    category,
    autoGenerated
  };
  
  bank.memories.unshift(newMemory); // 新记忆放在最前面
  
  // 如果超过最大记忆数，删除最旧的低重要性记忆
  if (bank.memories.length > bank.settings.maxMemories) {
    // 优先删除低重要性的记忆
    const lowImportance = bank.memories.filter(m => m.importance === 'low');
    if (lowImportance.length > 0) {
      const toDelete = lowImportance[lowImportance.length - 1];
      bank.memories = bank.memories.filter(m => m.id !== toDelete.id);
    } else {
      // 如果没有低重要性记忆，删除最旧的中等重要性记忆
      const mediumImportance = bank.memories.filter(m => m.importance === 'medium');
      if (mediumImportance.length > 0) {
        const toDelete = mediumImportance[mediumImportance.length - 1];
        bank.memories = bank.memories.filter(m => m.id !== toDelete.id);
      } else {
        // 删除最旧的记忆
        bank.memories.pop();
      }
    }
  }
  
  saveMemoryBank(bank);
  return newMemory;
};

/**
 * 删除记忆
 */
export const deleteMemory = (conversationId: string, memoryId: string): void => {
  const bank = getMemoryBank(conversationId);
  bank.memories = bank.memories.filter(m => m.id !== memoryId);
  saveMemoryBank(bank);
};

/**
 * 更新记忆的重要性
 */
export const updateMemoryImportance = (
  conversationId: string,
  memoryId: string,
  importance: 'low' | 'medium' | 'high'
): void => {
  const bank = getMemoryBank(conversationId);
  const memory = bank.memories.find(m => m.id === memoryId);
  if (memory) {
    memory.importance = importance;
    saveMemoryBank(bank);
  }
};

/**
 * 清空对话的所有记忆
 */
export const clearMemoryBank = (conversationId: string): void => {
  const bank = getMemoryBank(conversationId);
  bank.memories = [];
  bank.lastSummaryMessageCount = 0;
  bank.totalMessagesSinceLastSummary = 0;
  saveMemoryBank(bank);
};

/**
 * 更新记忆库设置
 */
export const updateMemorySettings = (
  conversationId: string,
  settings: Partial<MemoryBank['settings']>
): void => {
  const bank = getMemoryBank(conversationId);
  bank.settings = { ...bank.settings, ...settings };
  saveMemoryBank(bank);
};

/**
 * 检查是否需要自动总结
 */
export const shouldTriggerAutoSummary = (conversationId: string, currentMessageCount: number): boolean => {
  const bank = getMemoryBank(conversationId);
  
  if (!bank.settings.enableAutoSummary) {
    return false;
  }
  
  const messagesSinceLastSummary = currentMessageCount - bank.lastSummaryMessageCount;
  return messagesSinceLastSummary >= bank.settings.autoSummaryInterval;
};

/**
 * 更新总结计数器
 */
export const updateSummaryCounter = (conversationId: string, currentMessageCount: number): void => {
  const bank = getMemoryBank(conversationId);
  bank.lastSummaryMessageCount = currentMessageCount;
  bank.totalMessagesSinceLastSummary = 0;
  saveMemoryBank(bank);
};

/**
 * 生成记忆总结提示词
 */
export const buildMemorySummaryPrompt = (messages: Message[], existingMemories: MemoryEntry[]): string => {
  // 提取最近的对话内容（用于总结）
  const recentMessages = messages.slice(-30); // 最近30条消息
  
  let conversationText = '';
  recentMessages.forEach(msg => {
    const speaker = msg.role === 'user' ? '用户' : 'AI';
    let content = msg.content;
    
    // 处理特殊消息类型
    if (msg.mediaType === 'image' && msg.mediaDescription) {
      content = `[图片：${msg.mediaDescription}]`;
    } else if (msg.mediaType === 'voice' && msg.mediaDescription) {
      content = `[语音：${msg.mediaDescription}]`;
    } else if (msg.mediaType === 'video' && msg.mediaDescription) {
      content = `[视频：${msg.mediaDescription}]`;
    }
    
    conversationText += `${speaker}: ${content}\n`;
  });
  
  const existingMemoriesText = existingMemories.length > 0
    ? '\n\n【已有记忆】\n' + existingMemories.map(m => `- [${m.category || '其他'}] ${m.content}`).join('\n')
    : '';
  
  return `
【记忆总结任务】

请仔细分析以下对话，提取值得长期记忆的关键信息。

${existingMemoriesText}

【最近对话内容】
${conversationText}

【任务要求】
1. 提取以下类型的重要信息（如果有）：

**关于用户的记忆：**
   - 个人信息：用户的姓名、年龄、职业、家庭情况等基本信息
   - 喜好偏好：用户喜欢/不喜欢什么（食物、音乐、活动等）
   - 重要事件：用户提到的重要经历、计划、目标
   - 人际关系：用户提到的家人、朋友、同事等
   - 生活习惯：作息时间、日常习惯等
   - 情感状态：用户的情绪、压力、困扰等

**关于AI角色自己的记忆：**
   - AI提到的自己的经历和故事（如"我之前在课堂上吐槽老师"）
   - AI表达的观点、态度、喜好（如"我最喜欢的电影是..."）
   - AI提到的自己的人际关系（如"我的室友"、"我的老师"）
   - AI分享的个人感受和情绪
   - ⚠️ 重要：这些是AI在**本次对话中新提到的内容**，需要记住以便未来保持一致

**对话互动记忆：**
   - 重要的对话片段（用户问了什么重要问题，AI如何回答）
   - 共同的话题和讨论（如一起讨论某部电影、某个事件）
   - 有趣的互动和玩笑
   - 承诺和约定（如"下次一起去..."）

2. 每条记忆要求：
   - 简洁明确，一句话说清楚
   - 避免重复已有记忆
   - 只记录确定的信息，不要推测
   - 如果信息有更新，标注"更新："
   - **特别注意**：AI提到的自己的经历要详细记录，以便后续保持连贯

3. 重要性判断：
   - HIGH（高）：非常重要的个人信息、重大事件、核心喜好、AI的核心经历
   - MEDIUM（中）：一般性信息、日常事件、普通对话片段
   - LOW（低）：次要信息、可有可无的细节

【输出格式】
请严格按照以下JSON格式输出（不要添加任何其他文字）：
{
  "memories": [
    {
      "content": "记忆内容",
      "importance": "HIGH|MEDIUM|LOW",
      "category": "个人信息|喜好|事件|关系|习惯|情感|AI经历|AI观点|对话互动|其他"
    }
  ]
}

【示例】
如果对话中AI说："我上周在课堂上吐槽老师把PPT放反了，全班都笑疯了"
应该记录：
{
  "content": "AI上周在课堂上吐槽老师把PPT放反了，全班都笑了",
  "importance": "MEDIUM",
  "category": "AI经历"
}

如果用户后来问："你和那个老师关系还好吗？"
AI就能从记忆中知道"那个老师"指的是谁。

如果没有值得记忆的新信息，返回：
{
  "memories": []
}
`;
};

/**
 * 解析AI返回的记忆总结
 */
export const parseMemorySummaryResponse = (response: string): Array<{
  content: string;
  importance: 'low' | 'medium' | 'high';
  category?: string;
}> => {
  try {
    // 尝试提取JSON部分
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.warn('No JSON found in memory summary response');
      return [];
    }
    
    const parsed = JSON.parse(jsonMatch[0]);
    
    if (!parsed.memories || !Array.isArray(parsed.memories)) {
      return [];
    }
    
    return parsed.memories.map((m: any) => ({
      content: m.content,
      importance: (m.importance === 'HIGH' ? 'high' : m.importance === 'LOW' ? 'low' : 'medium') as 'low' | 'medium' | 'high',
      category: m.category
    }));
  } catch (error) {
    console.error('Failed to parse memory summary:', error);
    return [];
  }
};

/**
 * 构建记忆上下文（用于AI回复时）
 */
export const buildMemoryContext = (memories: MemoryEntry[]): string => {
  if (memories.length === 0) {
    return '';
  }
  
  // 按重要性和时间排序
  const sortedMemories = [...memories].sort((a, b) => {
    const importanceWeight = { high: 3, medium: 2, low: 1 };
    const weightDiff = importanceWeight[b.importance] - importanceWeight[a.importance];
    if (weightDiff !== 0) return weightDiff;
    return b.timestamp - a.timestamp; // 相同重要性按时间倒序
  });
  
  // 取最重要的前20条
  const topMemories = sortedMemories.slice(0, 20);
  
  let context = '\n【长期记忆库】\n';
  context += '以下是你和这位用户长期交往积累的记忆，包括关于用户的信息、你自己提到过的经历、以及你们之间的重要对话。\n';
  context += '请自然地运用这些记忆，保持角色的连贯性和一致性。\n\n';
  
  // 按分类整理
  const categories: Record<string, MemoryEntry[]> = {};
  topMemories.forEach(m => {
    const cat = m.category || '其他';
    if (!categories[cat]) {
      categories[cat] = [];
    }
    categories[cat].push(m);
  });
  
  // 定义分类顺序和说明
  const categoryOrder = [
    { key: 'AI经历', label: '关于你自己的经历', desc: '这些是你之前提到过的自己的故事和经历，请保持一致' },
    { key: 'AI观点', label: '你的观点和态度', desc: '你之前表达过的想法和喜好' },
    { key: '对话互动', label: '你们之间的互动', desc: '重要的对话片段、约定和共同话题' },
    { key: '个人信息', label: '关于用户', desc: '用户的基本信息' },
    { key: '喜好', label: '用户的喜好', desc: '' },
    { key: '事件', label: '用户的事件', desc: '' },
    { key: '关系', label: '用户的人际关系', desc: '' },
    { key: '习惯', label: '用户的习惯', desc: '' },
    { key: '情感', label: '用户的情感', desc: '' },
    { key: '其他', label: '其他记忆', desc: '' }
  ];
  
  // 按预定义顺序输出分类记忆
  categoryOrder.forEach(({ key, label, desc }) => {
    if (categories[key] && categories[key].length > 0) {
      context += `【${label}】\n`;
      if (desc) {
        context += `💡 ${desc}\n`;
      }
      categories[key].forEach(m => {
        const importance = m.importance === 'high' ? '⭐⭐⭐' : m.importance === 'medium' ? '⭐⭐' : '⭐';
        context += `${importance} ${m.content}\n`;
      });
      context += '\n';
    }
  });
  
  context += '**重要提示**：\n';
  context += '- 这些记忆是你和用户长期交往积累的，请自然地运用\n';
  context += '- **关于你自己的记忆**：如果用户提到你之前说过的经历（如"你上次说的那个老师"），你要能回忆起具体内容\n';
  context += '- **保持一致性**：你的观点、喜好、经历要与记忆保持一致，不要自相矛盾\n';
  context += '- 不要刻意展示记忆，而是在合适的时候自然提起\n';
  context += '- 如果用户提到相关话题，可以回忆起之前的对话\n';
  context += '- 避免重复询问你已经知道的信息\n';
  
  return context;
};

// 以下是为了兼容旧代码而保留的函数

/**
 * 从对话中提取记忆（旧版兼容）
 * @deprecated 使用新的自动总结系统
 */
export const extractMemoriesFromConversation = async (): Promise<any[]> => {
  console.warn('extractMemoriesFromConversation is deprecated, use auto summary instead');
  return [];
};

/**
 * 生成记忆总结（旧版兼容）
 * @deprecated 使用新的buildMemoryContext
 */
export const generateMemorySummary = async (): Promise<string> => {
  console.warn('generateMemorySummary is deprecated, use buildMemoryContext instead');
  return '';
};

/**
 * 应用记忆到对话上下文（旧版兼容，重定向到新函数）
 */
export const applyMemoriesToContext = (conversation: any, _memories: any[]): string => {
  const bank = getMemoryBank(conversation.id);
  return buildMemoryContext(bank.memories);
};

/**
 * 保存记忆到localStorage（旧版兼容）
 * @deprecated 使用saveMemoryBank
 */
export const saveMemories = (): void => {
  console.warn('saveMemories is deprecated, use saveMemoryBank instead');
};

/**
 * 从localStorage加载记忆（旧版兼容）
 * @deprecated 使用getMemoryBank
 */
export const loadMemories = (): any[] => {
  console.warn('loadMemories is deprecated, use getMemoryBank instead');
  return [];
};

/**
 * 添加新记忆（旧版兼容）
 * @deprecated 使用addMemory
 */
export const addMemories = (): any[] => {
  console.warn('addMemories is deprecated, use addMemory instead');
  return [];
};

/**
 * 获取对话的所有记忆（兼容函数）
 */
export const getConversationMemories = (conversationId: string): any[] => {
  const bank = getMemoryBank(conversationId);
  return bank.memories;
};

// ==================== 群聊记忆功能 ====================

/**
 * 检查是否需要触发群聊记忆总结
 */
export const shouldTriggerGroupMemorySummary = (
  conversationId: string,
  groupMessageCount: number
): boolean => {
  const bank = getMemoryBank(conversationId);
  const interval = bank.settings.groupSummaryInterval || 50; // 默认50条
  const lastCount = bank.lastGroupSummaryCount || 0;
  const messagesSinceLastSummary = groupMessageCount - lastCount;
  
  return messagesSinceLastSummary >= interval;
};

/**
 * 更新群聊总结计数器
 */
export const updateGroupSummaryCounter = (
  conversationId: string,
  currentGroupMessageCount: number
): void => {
  const bank = getMemoryBank(conversationId);
  bank.lastGroupSummaryCount = currentGroupMessageCount;
  bank.totalGroupMessagesSinceLastSummary = 0;
  saveMemoryBank(bank);
};

/**
 * 构建群聊记忆总结提示词
 */
export const buildGroupMemorySummaryPrompt = (
  groupName: string,
  aiName: string,
  messages: Message[],
  groupMembers: string[],
  existingGroupMemories: MemoryEntry[]
): string => {
  // 提取最近的群聊对话
  const recentMessages = messages.slice(-30); // 最近30条
  
  let conversationText = '';
  recentMessages.forEach(msg => {
    const msgWithSender = msg as any;
    const speaker = msgWithSender.senderName || (msg.role === 'user' ? '用户' : 'AI');
    let content = msg.content || '[媒体消息]';
    
    conversationText += `${speaker}: ${content}\n`;
  });
  
  const existingMemoriesText = existingGroupMemories.length > 0
    ? '\n\n【已有群聊记忆】\n' + existingGroupMemories.map(m => 
        `- [${m.category || '其他'}] ${m.content}`
      ).join('\n')
    : '';
  
  const membersText = groupMembers.join('、');
  
  return `
【群聊记忆总结任务】

你是"${aiName}"，这是你在群聊"${groupName}"的记忆总结。

【群聊信息】
- 群名：${groupName}
- 群成员：${membersText}

${existingMemoriesText}

【最近群聊对话】
${conversationText}

【总结要求】
请提取对"你"（${aiName}）有价值的记忆，包括：
1. 群友的性格特点、喜好、习惯
2. 群里讨论的重要话题和事件
3. 你参与的互动、约定、承诺
4. 群里的规则、习惯、氛围
5. 与你相关的特殊事件或经历

【输出格式】
严格按照以下JSON格式输出，不要有任何额外文字：
{
  "memories": [
    {
      "content": "具体的记忆内容",
      "category": "分类（如：群友信息、群聊话题、互动记录、群规则等）",
      "importance": "low/medium/high"
    }
  ]
}

注意：
- 只提取真正重要的信息，不要记录琐碎内容
- 每条记忆要简洁明了
- 重点记录与"你"（${aiName}）相关的内容
- 如果没有值得记忆的内容，返回空数组
`;
};

/**
 * 获取群聊记忆
 */
export const getGroupMemories = (conversationId: string, groupId?: string): MemoryEntry[] => {
  const bank = getMemoryBank(conversationId);
  return bank.memories.filter(m => {
    if (groupId) {
      return m.source === 'group' && m.groupId === groupId;
    }
    return m.source === 'group';
  });
};

/**
 * 获取私聊记忆
 */
export const getPrivateMemories = (conversationId: string): MemoryEntry[] => {
  const bank = getMemoryBank(conversationId);
  return bank.memories.filter(m => m.source === 'private' || !m.source);
};

/**
 * 添加群聊记忆
 */
export const addGroupMemory = (
  conversationId: string,
  groupId: string,
  groupName: string,
  content: string,
  category: string,
  importance: 'low' | 'medium' | 'high'
): void => {
  const bank = getMemoryBank(conversationId);
  
  const newMemory: MemoryEntry = {
    id: `group_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    timestamp: Date.now(),
    content,
    importance,
    category,
    autoGenerated: true,
    source: 'group',
    groupId,
    groupName
  };
  
  bank.memories.unshift(newMemory); // 新记忆放在最前面
  
  // 如果超过最大记忆数，删除最旧的低重要性记忆
  if (bank.memories.length > bank.settings.maxMemories) {
    const lowImportance = bank.memories.filter(m => m.importance === 'low');
    if (lowImportance.length > 0) {
      const toDelete = lowImportance[lowImportance.length - 1];
      bank.memories = bank.memories.filter(m => m.id !== toDelete.id);
    } else {
      // 如果没有低重要性记忆，删除最旧的
      bank.memories.pop();
    }
  }
  
  saveMemoryBank(bank);
};
