export interface ApiConfig {
  baseUrl: string;
  apiKey: string;
  modelName: string;
  // 语音转文字配置
  speechToText?: {
    enabled: boolean; // 是否启用语音转文字
    apiUrl?: string; // 语音识别API地址
    apiKey?: string; // 语音识别API Key
    model?: string; // 语音识别模型（如glm-4-flash）
  };
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  mediaType?: 'image' | 'video' | 'voice' | 'sticker'; // 媒体类型（新增sticker表情包）
  mediaDescription?: string; // AI的文字描述或用户的内容描述
  mediaUrl?: string; // 用户上传的真实媒体URL
  isMediaDescriptionOnly?: boolean; // 是否仅为文字描述（AI发送）
  voiceDuration?: number; // 语音时长（秒）
  isVoicePlayed?: boolean; // 语音是否已播放
}

export interface CharacterSettings {
  avatar?: string;
  nickname: string;
  username?: string; // 角色网名
  systemPrompt: string;
  personality: string;
  languageStyle: string;
  languageExample: string;
  memoryEvents: string;
  // AI主动发消息配置
  proactiveMessaging?: {
    enabled: boolean; // 是否启用
    minInterval: number; // 最小间隔（分钟）
    maxInterval: number; // 最大间隔（分钟）
    activeHourStart: number; // 活跃时段开始（小时，0-23）
    activeHourEnd: number; // 活跃时段结束（小时，0-23）
    lastMessageTime?: number; // 上次主动发消息的时间戳
  };
}

export interface Conversation {
  id: string;
  type: 'private' | 'group';
  name: string;
  avatar?: string;
  messages: Message[];
  characterSettings?: CharacterSettings;
  lastMessageTime: number;
  unreadCount: number;
  enabledFeatures?: string[];
  groupRemark?: string; // 群备注名（仅群聊）
  members?: string[]; // 群成员ID数组（仅群聊）
}

export interface UserProfile {
  avatar?: string;
  username: string;
  bio: string;
  coverImage?: string;
  avatarBadge?: string; // 头像装饰图标
  status?: string; // 在线状态
}

export interface MomentPost {
  id: string;
  authorId?: string; // 发布者ID（兼容旧版userId）
  userId?: string; // 旧版兼容
  authorName?: string; // 发布者名称（兼容旧版username）
  username?: string; // 旧版兼容
  authorAvatar?: string; // 发布者头像（兼容旧版userAvatar）
  userAvatar?: string; // 旧版兼容
  content: string;
  images?: string[]; // 图片URL数组
  imageDescriptions?: string[]; // AI生成的图片描述数组（用于纯文字描述图片）
  location?: string; // 位置信息
  timestamp: number;
  likes: string[];
  comments: MomentComment[];
  isRead?: boolean; // 是否已读
  mentionedUsers?: string[]; // @提到的用户ID数组
  // 扩展内容类型
  contentType?: 'text' | 'images' | 'music' | 'video' | 'link'; // 内容类型
  musicInfo?: { // 音乐分享信息
    title: string;
    artist: string;
    coverUrl?: string; // 封面图
  };
  videoInfo?: { // 视频信息
    coverUrl?: string; // 视频封面
    duration?: number; // 视频时长（秒）
  };
  linkInfo?: { // 链接分享信息
    title: string;
    description?: string;
    coverUrl?: string;
    url?: string;
  };
}

export interface MomentComment {
  id: string;
  authorId?: string; // 评论者ID（兼容旧版userId）
  userId?: string; // 旧版兼容
  authorName?: string; // 评论者名称（兼容旧版username）
  username?: string; // 旧版兼容
  authorAvatar?: string; // 评论者头像（兼容旧版userAvatar）
  userAvatar?: string; // 旧版兼容
  content: string;
  timestamp: number;
  replyTo?: string; // 回复的评论ID
  replyToName?: string; // 回复的用户名称
  replyToUsername?: string; // 旧版兼容
}

// 朋友圈数据库（每个联系人的朋友圈）
export interface MomentsData {
  contactId: string;
  posts: MomentPost[];
  lastGeneratedTime: number; // 上次生成朋友圈的时间
  lastGenerationDate: string; // 上次生成朋友圈的日期（YYYY-MM-DD）
  todayTargetCount: number; // 今天目标生成数量（1-5随机）
  todayGeneratedCount: number; // 今天已生成的数量
  scheduledTimes: number[]; // 今天计划发布的时间戳列表
  settings: {
    autoGenerate: boolean; // 是否自动生成
    minInterval: number; // 最小间隔（小时，24-72，即1-3天）
    maxInterval: number; // 最大间隔（小时）
    minPostsPerDay: number; // 每天最少发布数
    maxPostsPerDay: number; // 每天最多发布数
  };
}

// AI记忆条目
export interface MemoryEntry {
  id: string;
  timestamp: number; // 记忆创建时间
  content: string; // 记忆内容
  importance: 'low' | 'medium' | 'high'; // 重要性等级
  category?: string; // 分类（如：个人信息、喜好、事件、AI经历、对话互动等）
  relatedMessageIds?: string[]; // 关联的消息ID
  autoGenerated: boolean; // 是否由AI自动生成
}

// AI记忆库
export interface MemoryBank {
  conversationId: string; // 对话ID
  memories: MemoryEntry[];
  lastSummaryMessageCount: number; // 上次总结时的消息数量
  totalMessagesSinceLastSummary: number; // 距离上次总结的消息数量
  settings: {
    autoSummaryInterval: number; // 自动总结间隔（消息数量）
    maxMemories: number; // 最大记忆条目数
    enableAutoSummary: boolean; // 是否启用自动总结
  };
}

export type Screen = 'home' | 'settings' | 'social' | 'chat' | 'character-settings' | 'new-conversation' | 'profile' | 'moments' | 'contacts' | 'add-friend' | 'create-group' | 'theme' | 'guide';

export interface ThemeSettings {
  wallpaper: string;
  customWallpaper?: string;
  customBannerImage?: string; // 第二页的横幅图片
}
