export interface ApiConfig {
  baseUrl: string;
  apiKey: string;
  modelName: string;
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  mediaType?: 'image' | 'video' | 'voice'; // 媒体类型
  mediaDescription?: string; // AI的文字描述或用户的内容描述
  mediaUrl?: string; // 用户上传的真实媒体URL
  isMediaDescriptionOnly?: boolean; // 是否仅为文字描述（AI发送）
}

export interface CharacterSettings {
  avatar?: string;
  nickname: string;
  username?: string; // 角色网名
  systemPrompt: string;
  personality: string;
  languageStyle: string;
  languageExample: string;
  memoryEvents: string;
}

export interface Conversation {
  id: string;
  type: 'private' | 'group';
  name: string;
  avatar?: string;
  messages: Message[];
  characterSettings?: CharacterSettings;
  lastMessageTime: number;
  unreadCount: number;
  enabledFeatures?: string[];
  groupRemark?: string; // 群备注名（仅群聊）
  members?: string[]; // 群成员ID数组（仅群聊）
}

export interface UserProfile {
  avatar?: string;
  username: string;
  bio: string;
  coverImage?: string;
  avatarBadge?: string; // 头像装饰图标
  status?: string; // 在线状态
}

export interface MomentPost {
  id: string;
  authorId?: string; // 发布者ID（兼容旧版userId）
  userId?: string; // 旧版兼容
  authorName?: string; // 发布者名称（兼容旧版username）
  username?: string; // 旧版兼容
  authorAvatar?: string; // 发布者头像（兼容旧版userAvatar）
  userAvatar?: string; // 旧版兼容
  content: string;
  images?: string[];
  location?: string; // 位置信息
  timestamp: number;
  likes: string[];
  comments: MomentComment[];
  isRead?: boolean; // 是否已读
  mentionedUsers?: string[]; // @提到的用户ID数组
}

export interface MomentComment {
  id: string;
  authorId?: string; // 评论者ID（兼容旧版userId）
  userId?: string; // 旧版兼容
  authorName?: string; // 评论者名称（兼容旧版username）
  username?: string; // 旧版兼容
  authorAvatar?: string; // 评论者头像（兼容旧版userAvatar）
  userAvatar?: string; // 旧版兼容
  content: string;
  timestamp: number;
  replyTo?: string; // 回复的评论ID
  replyToName?: string; // 回复的用户名称
  replyToUsername?: string; // 旧版兼容
}

// 朋友圈数据库（每个联系人的朋友圈）
export interface MomentsData {
  contactId: string;
  posts: MomentPost[];
  lastGeneratedTime: number; // 上次生成朋友圈的时间
  generatedCountToday: number; // 今天已生成的数量
  settings: {
    autoGenerate: boolean; // 是否自动生成
    minInterval: number; // 最小间隔（小时）
    maxInterval: number; // 最大间隔（小时）
    minPostsPerCycle: number; // 每周期最少发布数
    maxPostsPerCycle: number; // 每周期最多发布数
  };
}

// AI记忆条目
export interface MemoryEntry {
  id: string;
  timestamp: number; // 记忆创建时间
  content: string; // 记忆内容
  importance: 'low' | 'medium' | 'high'; // 重要性等级
  category?: string; // 分类（如：个人信息、喜好、事件、AI经历、对话互动等）
  relatedMessageIds?: string[]; // 关联的消息ID
  autoGenerated: boolean; // 是否由AI自动生成
}

// AI记忆库
export interface MemoryBank {
  conversationId: string; // 对话ID
  memories: MemoryEntry[];
  lastSummaryMessageCount: number; // 上次总结时的消息数量
  totalMessagesSinceLastSummary: number; // 距离上次总结的消息数量
  settings: {
    autoSummaryInterval: number; // 自动总结间隔（消息数量）
    maxMemories: number; // 最大记忆条目数
    enableAutoSummary: boolean; // 是否启用自动总结
  };
}

export type Screen = 'home' | 'settings' | 'social' | 'chat' | 'character-settings' | 'new-conversation' | 'profile' | 'moments' | 'contacts' | 'add-friend' | 'create-group' | 'theme' | 'guide';

export interface ThemeSettings {
  wallpaper: string;
  customWallpaper?: string;
  customBannerImage?: string; // 第二页的横幅图片
}
